# Generated by Django 4.2.6 on 2023-12-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_department_employee_delete_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
            ],
        ),
    ]
